### ISSUE TITLE
Add indicator of uncommited changes?

### ISSUE THREAD

**Issue by rbresalier** [lessthanoptimal/gversion-plugin#5]
I saw a different gradle plugin - https://github.com/palantir/gradle-git-version, is able to identify if there are uncommitted changes and it will add ".dirty" when that is detected.

Would that be possible with gversion-plugin? I like how it generates a .java file where I can access the SHA hash at runtime, I'd also like to have possibly another string in the generated file to indicated "dirty" - uncommitted changes.

**Comment by lessthanoptimal** [comment]
Good idea. Just added it and let me know if you like how it's implemented. I'm not sure of it using an `int` instead of a `String`.  String would be more human readable but i didn't like how people would need to hard code a String to see if its clean or not. Couldn't use a boolean since I needed some way to indicate that it couldn't determine if it was dirty or not.

**Comment by rbresalier** [comment]
Thanks! I like it very much. int is fine. Tested it out and it properly detects dirty (1) and no uncommitted changes (0). Thanks for changing this so quickly!
